export const itemsList: Items = {
  14047: {
    name: 'Runecloth',
    gerName: 'Runenstoff',
    stackSize: 20,
    furtherWork: 18629,
    amount: 10,
    price: 0,
  },
  18629: {
    name: 'Runecloth Bandage',
    gerName: 'Runenstoffverband',
    stackSize: 20,
    amount: 10,
    price: 0,
  },
  4306: {
    name: 'Silk Cloth',
    gerName: 'Seidenstoff',
    stackSize: 20,
    furtherWork: 6450,
    amount: 5,
    price: 0,
  },
  6450: {
    name: 'Silk Bandage',
    gerName: 'Seidenverband',
    stackSize: 20,
    amount: 5,
    price: 0,
  },
  4304: {
    name: 'Thick Leather',
    gerName: 'Dickes Leder',
    stackSize: 10,
    amount: 7,
    price: 0,
  },
  2319: {
    name: 'Medium Leather',
    gerName: 'Mittleres Leder',
    stackSize: 10,
    amount: 3,
    price: 0,
  },
  2318: {
    name: 'Light Leather',
    gerName: 'Leichtes Leder',
    stackSize: 10,
    amount: 1,
    price: 0,
  },
  10620: {
    name: 'Thorium Ore',
    gerName: 'Thoriumerz',
    stackSize: 20,
    amount: 10,
    price: 0,
    furtherWork: 12359,
  },
  12359: {
    name: 'Thorium Bar',
    gerName: 'Thoriumbarren',
    stackSize: 20,
    amount: 10,
    price: 0,
  },
  3820: {
    name: 'Stranglekelp',
    gerName: 'Würgetang',
    stackSize: 20,
    amount: 3,
    price: 0,
  },
  8831: {
    name: 'Purple Lotus',
    gerName: 'Lila Lotus',
    stackSize: 20,
    amount: 7,
    price: 0,
  },
  8836: {
    name: 'Arthas Tear',
    gerName: "Arthas' Tränen",
    stackSize: 20,
    amount: 10,
    price: 0,
  },
  6887: {
    name: 'Spotted Yellowtail',
    gerName: 'Tüpfelgelbschwanz',
    stackSize: 20,
    amount: 7,
    price: 0,
  },
  4603: {
    name: 'Raw Spotted Yellowtail',
    gerName: 'Roher Tüpfelgelbschwanz',
    stackSize: 20,
    amount: 7,
    price: 0,
    furtherWork: 6887,
  },
}
